apiVersion: v1
kind: Pod


metadata:
        name: frontend
        labels:
                app: frontend

spec:
        containers:
        - name: frontend
          image: regmicmahesh/frontend:latest
          ports:
          - name: webport
            containerPort: 80 

