apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
        name: total-ingress

spec:
        rules:
                - host: details.com
                  http:
                          paths:
                                  - path: /
                                    pathType: 

